name: Docker CI

on:
  pull_request:
    paths:
      - .github/workflows/docker-ci.yaml
      - build.sbt

jobs:
  docker-build:
    strategy:
      matrix:
        platform: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.9.9
      - name: Build Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}
        run: sbt docker/Docker/publishLocal
      - name: Test Docker image
        run: docker run --rm --entrypoint=/usr/bin/java $(docker images -q | head -n1) -version
